% Derives the 3D effective speed for many cases of exact_time_domain_solution_surf_direct_paths.m
%
% INPUTS
%
% c               1 x 1.  speed of sound in water (m/s)
% src_xz          1 x 2.  x = src_xz(1) (m) and z=src_xz(2) (m) are the horizontal and vertical coordinates of a source.
%                         z is 0 at ocean's surface and is positive up.  source also located at y=0,  in 3D space.
% rec_x_bnds      1 x 2.  Bounds for x coordinate of receiver (m). Min value in column 1.
% rec_z_bnds      1 x 2.  Bounds for Vertical coordinate of receiver (m). Same coordinate system as for src_z
% nx              1 x 1.  Receiver x coordinate will be simulated nx times in rec_x_bnds
% nz              1 x 1.    "      z    "       "       "       " nz    "     rec_z_bnds 
% tau             1 x 1.  emitted pulse is exp(-(t/tau)^2)*cos(omega*t) with tau in seconds and t in seconds
% omega           1 x 1.  See tau above. Units are rad/s
% g_base          1 x 1.  The base g value for each element in the field generated by samp_freq_mult_fied.m, where the
%                         sample frequency of synthsized time series will equal g * omega/(2*pi). g must be >=2.
% g_mult          1 x 1.  The peak multiplier of g to be used near the foci (see samp_freq_mult_field.m). i.e. the 
%                         elements closest to the foci will have a g value of g_base*g_mult
% cheby           1 x 1.  The Chebyshev distance (in units of g field indecies) from the g-field xz index pair nearest  
%                         to the foci which shall be elevated from g_base. I.e. If a focus is nearest to g field's xz 
%                         index pair (2, 2), and cheby = 1, all indecies in the square with opposing corners (1, 1) and 
%                         (3, 3) will be elevated. cheby must be >= 3.
% mult_type       1 x 1.  A numerical identifier to determine how the elevation changes with distance from the xz index
%                         pair nearest to a foci.   0: uniform elevation. each index in range is multiplied by g_mult
%                                                   1: linear. the centermost 3 x 3 index box will be multiplied by
%                                                      g_mult, and each box an additional step outwards will linearly 
%                                                      decrease to g_base
% boundary_type   1 x 1.  1: boundary is like surface of ocean where there are no pressure fluctuations.
%                            There is a direct path and a path reflecting from surface 
%                         2: boundary is hard. Reflected path bounces from hard flat rocks on bottom of ocean.
% fign            1 x 1.  Figure number for plot. If empty, no plots shown
%
% OUTPUTS
%
% ierr          0: No error detected. 1: otherwise
%
function [ierr]=c3d_exact_many_cases(c,src_xz,rec_x_bnds,rec_z_bnds,nx,nz,tau,omega,g_base, g_mult,cheby, ...
    mult_type,boundary_type,fign)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Preliminary Steps
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
progname='c3d_exact_many_cases.m';

dotest=0;
if(dotest==1)
  fprintf(1,'%s: Test case. Press Enter to continue\n',progname);pause
  c=1480;
  scenario=17;
  switch scenario
      case 0
      % Yields c3d bounds 
          src_xz=-20;
          rec_x_bnds=[-10 10];
          rec_z_bnds=[-25 -10];
          nx=100;
          nz=100;
          tau=0.025;
          omega=95*2*pi;
          samp_freq_mult=10000;
          boundary_type=1;
      case 1
          % Yields c3d bounds 
          src_xz=-20;
          rec_x_bnds=[0.01 100];
          rec_z_bnds=[-20 -5];
          nx=100;
          nz=30;
          tau=0.025;
          omega=100*2*pi;
          samp_freq_mult=10000;
          boundary_type=1;
     
       case 2
          % Yields c3d bounds 
          src_xz=-2;
          rec_x_bnds=[0.01 100];
          rec_z_bnds=[-20 -0.1];
          nx=100;
          nz=30;
          tau=0.025;
          omega=100*2*pi;
          samp_freq_mult=10000;
          boundary_type=1;
          
       case 3
          % Yields c3d bounds 
          src_xz=-2;
          rec_x_bnds=[0.01 100];
          rec_z_bnds=[-20 -0.1];
          nx=100;
          nz=30;
          tau=0.25;
          omega=20*2*pi;
          samp_freq_mult=10000;
          boundary_type=1;
          
      case 4
          % Like scenario 3 except increase center freq from 20 to 1000 Hz
          % Yields c3d bounds 
          src_xz=-2;
          rec_x_bnds=[0.01 100];
          rec_z_bnds=[-20 -0.1];
          nx=100;
          nz=30;
          tau=0.25;
          omega=1000*2*pi;
          samp_freq_mult=10000;
          boundary_type=1;
          
      case 5
          % Identical to scenario 4 except make hard boundary
          % Yields c3d bounds 
          % Plot shows min value when receiver near source
          src_xz=-2;
          rec_x_bnds=[0.01 100];
          rec_z_bnds=[-20 -0.1];
          nx=100;
          nz=30;
          tau=0.25;
          omega=1000*2*pi;
          samp_freq_mult=10000;
          boundary_type=2;
          
      case 6
          % Identical to scenario 5 except look at receiver locs very near source
          % Yields c3d bounds 
          % Very near source, speeds are inifnite, not 0, which means propagation time of  peak is 0
          % Plot shows min value when receiver near source
          src_xz=-2;
          rec_x_bnds=[0.0001 1];
          rec_z_bnds=[-2.5 -1.5];
          nx=10;
          nz=21;
          tau=0.25;
          omega=1000*2*pi;
          samp_freq_mult=10000;
          boundary_type=2;
          
       case 7
          % Identical to scenario 6 except omega is 2*2*pi instead of 1000*2*pi
          % Yields c3d bounds 
          % Very near source, speeds are inifnite, not 0, which means propagation time of  peak is 0
          % Plot shows min value when receiver near source
          src_xz=-2;
          rec_x_bnds=[0.0001 1];
          rec_z_bnds=[-2.5 -1.5];
          nx=10;
          nz=21;
          tau=0.25;
          omega=2*2*pi;
          boundary_type=2;
          
        case 8
          % Identical to scenario 6 except omega is 0.1*2*pi instead of 1000*2*pi
          % Yields c3d bounds 
          % Very near source, speeds are inifnite, not 0, which means propagation time of  peak is 0
          % Plot shows min value when receiver near source
          src_xz=-2;
          rec_x_bnds=[0.0001 1];
          rec_z_bnds=[-2.5 -1.5];
          nx=10;
          nz=21;
          tau=0.25;
          omega=0.1*2*pi;
          samp_freq_mult=20000000;
          boundary_type=2;
      case 9
          % Identical to scenario 8 except samp_freq_mult=50000
          % Yields c3d bounds 
          % Very near source, speeds are inifnite, not 0, which means propagation time of  peak is 0
          % Plot shows min value when receiver near source
          src_xz=-2;
          rec_x_bnds=[0.0001 1];
          rec_z_bnds=[-2.5 -1.5];
          nx=10;
          nz=21;
          tau=0.25;
          omega=0.1*2*pi;
          samp_freq_mult=5000000;
          boundary_type=2;
          
        case 10
          % Source close to surface. Surface is hard
          % Yields c3d bounds 
       
          % Plot shows min value when receiver near source
          src_xz=-0.1;
          rec_x_bnds=[0.00001 0.1];
          rec_z_bnds=[-0.010 -0.12];
          nx=5;
          nz=21;
          tau=0.25;
          omega=0.1*2*pi;
          samp_freq_mult=10000000;
          boundary_type=2;

      case 11
          % Source close to surface. Surface is hard
          % Yields c3d bounds 
          % Plot shows min value when receiver near source
          % 100 Hz center  freq
          src_xz=-0.1;
          rec_x_bnds=[0.00001 0.1];
          rec_z_bnds=[-0.010 -0.12];
          nx=5;
          nz=21;
          tau=0.25;
          omega=100*2*pi;
          g_base=1000;
          g_mult = 5;
          boundary_type=2;

      case 12
           % Yields c3d bounds  1135 to 3176 m/s
          src_xz=-20;
          rec_x_bnds=[1 100];
          rec_z_bnds=[-20 -5];
          nx=10;
          nz=5;
          tau=0.025;
          omega=100*2*pi;
          samp_freq_mult=10000;
          boundary_type=1;
      case 15
          % Yields c3d bounds  1034.55 to 2431.5 m/s
          src_xz=[0 -20];
          rec_x_bnds=[0.3 1];
          rec_z_bnds=[-20 -1];
          nx=3;
          nz=5;
          tau=0.025;
          omega=100*2*pi;
          samp_freq_mult=10000;
          boundary_type=2;
      case 16
          %mine Yields c3d bounds  1005 to 3478 m/s
          src_xz=[0 -20];
          rec_x_bnds=[1 40];
          rec_z_bnds=[-20 -5];
          nx=50;
          nz=50;
          tau=0.025;
          omega=93*2*pi;
          samp_freq_mult=10000;
          boundary_type=1;
      case 17
          %mine Yields c3d bounds  1292 to 3478 m/s
          c=1500;
          src_xz=[5 -50];
          rec_x_bnds=[10 350];
          rec_z_bnds=[-150 -1];
          nx = 100;
          nz=70;
          tau=0.025;
          omega=93*2*pi;
          g_base=2000;
          g_mult = 5;
          boundary_type=1;
      otherwise
          fprintf(1,'%s: software not written for scenario=%d\n',progname,scenario);

  end % switch scenario
  fign=1;
  close all
end

% Initialize outputs
ierr=0;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Do work
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Allocate memory
c3d=nan(nx,nz);

% make a field of 'g' values to reeduce compute time
foci_xz = src_xz;
[gf,ierr]=samp_freq_mult_field(foci_xz,rec_x_bnds,rec_z_bnds,nx,nz,g_base, g_mult, cheby, mult_type);
if ierr ==1
    fprintf(1,'%s: Error detected in samp_freq_mult_field.m\m',progname)
    return
end
% Generate x coords of receiver
rec_x=linspace(rec_x_bnds(1),rec_x_bnds(2),nx);
% Generate z coords of receivers
rec_z=linspace(rec_z_bnds(1),rec_z_bnds(2),nz);

fign_exact=[];
% Fill c3d
for ix=1:nx
    fprintf(1,'%s: Start ix = %d of %d\n',progname,ix,nx);
    % Allocate memory to store error from exact_time_domain_solution_refleted_direct_paths.m
    ierr_all=zeros(1,nz);
    
    parfor iz=1:nz
        % Derive xz coord of receiver
        rec_xz=[rec_x(ix) rec_z(iz)];

        %get a value of samp_freq_mult from the g_field
        gi = gf(iz, ix);
        [h,ierr_all(iz)]=exact_time_domain_solution_reflected_direct_paths(c,src_xz,rec_xz,tau,omega,gi,...
            boundary_type,fign_exact);
        
        if(~isempty(fign_exact))
            fprintf(1,'%s: Pausing. Press ENTER to plot next case.\n',progname);
            pause
        end
        % Store c3d
        if(ierr_all(iz)==0)
            c3d(ix,iz)=h.c3d;
        end
    end % for iz=1:nz
    if(sum(abs(ierr_all))>0)
        fprintf(1,'%s: At least one error returned from exact_time_domain_solution_reflected_direct_paths.m.\n',...
            progname);
        fprintf(1,' Pausing so you can fix problem.\n');
        pause
    end
end % for ix=1:nx

%-----------------------------------------------------------------------------------------------------------------------
% derive location of receiver with min value of c3d: xy_c3d_min
%-----------------------------------------------------------------------------------------------------------------------
[c3d_min,k]=min(c3d,[],'all','linear');
% Get linear index
[ix,iz]=ind2sub(size(c3d),k);
xy_c3d_min=[rec_x(ix) rec_z(iz)];

%-----------------------------------------------------------------------------------------------------------------------
% Plot  evelope of  received signal where c3d  is minimum
%-----------------------------------------------------------------------------------------------------------------------
rec_xz=[rec_x(ix) rec_z(iz)];
fign_exact=[];
gi = gf(iz, ix);
[h,ierr]=exact_time_domain_solution_reflected_direct_paths(c,src_xz,rec_xz,tau,omega,gi,...
    boundary_type,fign_exact);
if ~isempty(fign_exact)
    figure(fign_exact)
    sgtitle(['Waveform received at Min c3d (' num2str(c3d_min, '%.1f') ' m/s)']);
end

if(ierr~=0),return,end

fprintf(1,'c3d  is min = %f m/s when source and receiver separated by %f m.\n',c3d_min,h.l_direct);

%-----------------------------------------------------------------------------------------------------------------------
% derive location of receiver with max value of c3d: xy_c3d_max
%-----------------------------------------------------------------------------------------------------------------------
% change any Inf values in c3d to -Inf
c3d_clean = c3d;
c3d_clean(isinf(c3d_clean)) = -Inf;
%find the max and print warning if it is still -Inf
[c3d_max,k]=max(c3d_clean,[],'all','linear');
if c3d_max == -Inf
    fprintf(1, '%s: WARNING! max value of c3d is -Inf',progname)
    ierr = 1;
    return
end
% Get linear index
[ix,iz]=ind2sub(size(c3d),k);
xy_c3d_max=[rec_x(ix) rec_z(iz)];

%-----------------------------------------------------------------------------------------------------------------------
% Plot  evelope of  received signal where c3d  is MAXIMUM if fign_exact_max is not empty
%-----------------------------------------------------------------------------------------------------------------------

rec_xz_max=[rec_x(ix) rec_z(iz)];
fign_exact_max=[];
gi = gf(iz, ix);
[h_max,ierr]=exact_time_domain_solution_reflected_direct_paths(c,src_xz,rec_xz_max,tau,omega,gi,...
    boundary_type,fign_exact_max);
if ~isempty(fign_exact_max)
    figure(fign_exact_max)
    sgtitle(['Waveform received at Max c3d (' num2str(c3d_max, '%.1f') ' m/s)']);
end
if(ierr~=0),return,end

fprintf(1,'c3d  is max = %f m/s when source and receiver separated by %f m.\n',c3d_max,h_max.l_direct);

%-----------------------------------------------------------------------------------------------------------------------
% Compute cross-correlation between emitted and received signals and fix lag corresponding to max of abs value
% hilbert transform
%-----------------------------------------------------------------------------------------------------------------------
% Cross correlate
[z]=xcorr(h_max.s,h_max.s_emit,'biased');
% [z]=xcorr(h_max.s_emit,h_max.s_emit,'biased');
% Get abs value of hilbert transform of z
abs_h_z=abs(hilbert(z));
% Find maximum  peak
[~,ind_pk_max]=max(abs_h_z);
% get length of h_max.s)
ns=length(h_max.s);
% Get lag axis for abs_h_z: lag_axis
lag_axis=1:length(abs_h_z);
% lag is zero at index ns of abs_h_z
lag_axis=(lag_axis - lag_axis(ns))*diff(h_max.taxis(1:2));
% Derive lag of peak
lag_pk_max=lag_axis(ind_pk_max);

%-----------------------------------------------------------------------------------------------------------------------
% Plot ccf and  its hilbert transform if desired
%-----------------------------------------------------------------------------------------------------------------------
fign_ccf = [];
if ~isempty(fign_ccf)
    clf(fign_ccf);
    plot(lag_axis,z,'k-');
    hold on
    plot(lag_axis,abs_h_z,'g-');
    % Plot peak
    plot(lag_pk_max,abs_h_z(ind_pk_max),'r.');
    xlabel("lag (s)");
    ylabel('Abs value Hilbert Tranform CCF \color{red}  peak')
    title('CCf of emitted and received waveforms for c3d max value')
    saveas(4,'abs_hil_ccf','fig');
end %~isempty(fign_ccf)
fprintf(1,' for c3d_max, TDOA between emitted and received peaks of hilbert transform =  %f s\n',h_max.t_r)
fprintf(1,'              Using cross-correlation of waveforms, peak  of Hilbert transf = %f s\n',lag_pk_max);

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Plot if wanted
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
if(~isempty(fign))
    figure(fign);
    clf(fign);
    %surf(rec_z,rec_x,c3d);
    surf(rec_x,rec_z,c3d','facealpha',0.5,'EdgeColor','none');
    
    xlabel('X (m)');
    ylabel('Z (m)');
    zlabel('c3d (m/s)');
    %set(gca,'Xdir','reverse');
    
    V=axis;
    hold on;
    % Plot location where c3d is minimum
    plot3(xy_c3d_min(1),xy_c3d_min(2),c3d(k),'k*');
    % Plot source location
    plot3([0 0],[src_xz(2) src_xz(2)],V(5:6),'k-','linewidth',2);
    grid on
    colormap('gray');
    
    title(['Min/max c3d = ' num2str(min(c3d,[],'all')) '  ' num2str(max(c3d_clean,[],'all')) ' Min *']);
    
    % Save plot if ran for a test case
    if dotest == 1
        fnam=['scenario_' num2str(scenario)];
        saveas(fign,fnam);
        % Save variables in mat file
        s=['save ' fnam '.mat'];
        eval(s);
    end
end
