% This subroutine will generate an isodiachron (points of equal difference in time taken for a signal to reach two 
% receivers) for a constant in-situ speed of sound.
%
% INPUTS
%
% c               1 x 1.  in-situ speed of sound in water (m/s)
% src_xz          1 x 2.  x = src_xz(1) (m) and z=src_xz(2) (m) are the horizontal and vertical coordinates of a source.
%                         z is 0 at ocean's surface and is positive up.  source also located at y=0,  in 3D space.
% rec_1_xz        1 x 2.  The first receiver's horizontal (rec_1_xz(1)) and vertical coordinate (rec_1_xz(2)). Same 
%                         coordinate system as for src_xz             
% rec_2_xz        1 x 2.  Same arrangment as rec_1_xz, but for the second receiver
% tau             1 x 1.  emitted pulse is exp(-(t/tau)^2)*cos(omega*t) with tau in seconds and t in seconds
% omega           1 x 1.  See tau above. Units are rad/s
% g_base          1 x 1.  The base g value for each element in the field generated by samp_freq_mult_fied.m, where the
%                         Sample frequency of synthsized time series will equal g * omega/(2*pi). g must be >=2.
% g_mult          1 x 1.  The peak multiplier of g to be used near the foci (see samp_freq_mult_field.m). i.e. the 
%                         elements closest to the foci will have a g value of g_base*g_mult
% cheby           1 x 1.  The Chebyshev distance (in units of g field indecies) from the g-field xz index pair nearest  
%                         to the foci which shall be elevated from g_base. I.e. If a focus is nearest to g field's xz 
%                         index pair (2, 2), and cheby = 1, all indecies in the square with opposing corners (1, 1) and 
%                         (3, 3) will be elevated. cheby must be >= 3.
% mult_type       1 x 1.  A numerical identifier to determine how the g elevation changes with distance from an xz index
%                         pair nearest to a focus.  0: uniform elevation. each index in range is multiplied by g_mult
%                                                   1: linear. the centermost 3 x 3 index box will be multiplied by
%                                                      g_mult, and each box an additional step outwards will linearly 
%                                                      decrease to g_base
% boundary_type   1 x 1.  1: boundary is like surface of ocean where there are no pressure fluctuations.
%                            There is a direct path and a path reflecting from surface 
%                         2: boundary is hard. Reflected path bounces from hard flat rocks on bottom of ocean.
% x_bnds          1 x 2.  The minimum (x_bnds(1)) and maximum (x_bnds(2)) bounds on the x-coordinate of a region in the
%                         xz-plane for which the source is expected (i.e. the region to be plotted)
% z_bnds          1 x 2.  The minimum (z_bnds(1)) and maximum (z_bnds(2)) bounds on the z-coordinate of a region in the
%                         xz-plane for which the source is expected (i.e. the region to be plotted)
% xz_res          1 x 1   The number of points to divide the x and z bounds into. The higher the number the more points
%                         evaluated at.
% td              1 x 1.  The time difference of arrival of a signal between 2 receivers
% td_type         1 x 1.  Parameter to identify how the tdoa was determined.
%                           0: difference in arrival times of peaks of incoming energy received by each receiver
%                           1: peak lag given by cross correlation of the signal received by the receivers
% fign            1 x 1.  Figure number for plot. If empty, no plots shown.
%
% OUTPUTS
%
% isd_coords      1 x q   Cell array with cells:
%
% - isd_coords{i} 2 x n.  isd_coords{i}(1,j) is the x coordinate of the j'th point on the i'th isodiachron.
%                         isd_coords{i}(2,j)   "    z      "       "       "       "       "       "
%
% ierr            0: No error detected. 1: otherwise

function [isd_coords, ierr] = isodiachron_xz_from_tdoa_cst_c(c,src_xz,rec_1_xz, rec_2_xz, tau, omega, g_base, ...
    g_mult, cheby, mult_type, boundary_type, x_bnds, z_bnds, xz_res, td, td_type, fign)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% PRELIMINARY STEPS
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
progname='isodiachron_xz_from_tdoa_cst_c.m';
%fprintf (1, '%s: See cags6131.mat to debug.  Pausing\n', progname);save cags6131; pause

dotest=0;
if(dotest==1)
    fprintf(1,'%s: Test case. Press Enter to continue\n',progname);pause
    c=1480;
    fign = [];
    
    scenario=3;
    switch scenario

       
        case 3 %no hyperbola USE THIS
            src_xz=[5 -50];
            rec_1_xz=[80 -70];
            rec_2_xz=[250 -70];
            tau=0.025;
            omega=93*2*pi;
            g_base=2000;
            g_mult = 3;
            g = g_base*g_mult;
            boundary_type=1;
            x_bnds = [-50 350];
            z_bnds = [-120 0];
            xz_res = 45;  


            [h1,~]=exact_time_domain_solution_reflected_direct_paths(c,src_xz,rec_1_xz,tau,omega,g,boundary_type,fign);
            [h2,~]=exact_time_domain_solution_reflected_direct_paths(c,src_xz,rec_2_xz,tau,omega,g,boundary_type,fign);
            s1 = h1.s;
            s2 = h2.s;
            fs = g*omega/(2*pi);
            [td,~]=plot_ah_ccf_same_samp_freq(s1,s2,fs,fign);
            td_type = 1;
          
        otherwise
        fprintf(1,'%s: software not written for scenario=%d\n',progname,scenario);
        pause
    end % switch scenario
    
    fign=4;
end

% Initialize outputs
isd_coords = {[]};
ierr = 0;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Make isodiachron
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% allocate memory
tdoas = nan(xz_res, xz_res);
% Create a grid to set g at each point on grid
x = linspace(x_bnds(1), x_bnds(2), xz_res);
z = linspace(z_bnds(1), z_bnds(2), xz_res);
% make the field of 'g' values to optimize time
foci_xz = [rec_1_xz; rec_2_xz];
[gf,ierr]=samp_freq_mult_field(foci_xz,x_bnds,z_bnds,xz_res,xz_res,g_base, g_mult, cheby, mult_type);
if ierr ==1
    fprintf(1,'%s: Error detected in samp_freq_mult_field.m\m',progname)
    return
end
%hardcode fign_exact if you want intermediate plots
fign_exact = [];

% workflow depends on value of td_type
switch td_type
    %-------------------------------------------------------------------------------------------------------------------
    % td_type = 0: arrival time difference of peaks of arriving energy
    %-------------------------------------------------------------------------------------------------------------------
    case 0 
        % Calculate the would-be arrival time of the first energetic peak from a source at each position in the grid
        for ix = 1:xz_res
            fprintf(1,'%s: Start ix = %d of %d\n',progname,ix,xz_res);
            % Allocate memory to store error from exact_time_domain_solution_refleted_direct_paths.m
            ierr_all=zeros(1,xz_res);
            src_x_i = x(ix);
            parfor iz=1:xz_res
                %set up source coords and select a g value
                src_z_i = z(iz);
                src_xz_i = [src_x_i src_z_i];
                gi = gf(iz, ix);
                %simulate the signals from source to each receiver
                [h1,ierr_1]=exact_time_domain_solution_reflected_direct_paths(c,src_xz_i,rec_1_xz,tau,omega,gi, ...
                    boundary_type, fign_exact);
                [h2,ierr_2]=exact_time_domain_solution_reflected_direct_paths(c,src_xz_i,rec_2_xz,tau,omega,gi, ...
                    boundary_type, fign_exact);
                %check for errors
                if ierr_1 || ierr_2
                    ierr_all(iz) = 1;
                end %ierr_1 || ierr_2
                %plot if desired
                if(~isempty(fign_exact))
                    fprintf(1,'%s: Pausing. Press ENTER to plot next case.\n',progname);
                    pause
                end
                % calculate tdoa
                tm1 = h1.t_r;
                tm2 = h2.t_r;
                td_i = tm2 - tm1;
                % Store tdoa
                if(ierr_all(iz)==0)
                    tdoas(iz,ix)=td_i;
                end
            end % parfor iz=1:n
            if(sum(abs(ierr_all))>0)
                fprintf(1,['%s: At least one error returned from ' ...
                    'exact_time_domain_solution_reflected_direct_paths.m.\n'],...
                    progname);
                fprintf(1,' Pausing so you can fix problem.\n');
                pause
            end
        end %for ix = 1:xz_res
        
        % Make a contour at the inputted distance in difference
        t_level = [td td];
        M = contourc(x, z, tdoas, t_level);
        
        %make sure the isodiachron contours arent empty
        if ~isempty(M)
            % Fix the formatting of the M matrix so that the only points are the points that fall in the contour
            i = 1;
            while i < size(M,2)
                %unpack M's i'th contour
                n_points = M(2,i);
                x_vals = M(1, i+1 : i+n_points);
                z_vals = M(2, i+1 : i+n_points);
                %fill isd_coords
                if isempty(isd_coords{1})
                    isd_coords{1} = [x_vals; z_vals];
                else
                    isd_coords{end+1} = [x_vals; z_vals];
                end
                i = i + n_points + 1;
            end
        else
            %if it is empty, return an error
            fprintf(1,'%s: Isodiachron contains 0 points. Input xz_res value of %d may be too small.\n',progname,xz_res)
            ierr = 1;
            return
        end %if ~isempty(M)
    %-------------------------------------------------------------------------------------------------------------------
    % td_type = 1: cross correaltion
    %-------------------------------------------------------------------------------------------------------------------
    case 1 
        % Calculate the would-be arrival time of the first energetic peak from a source at each position in the grid
        for ix = 1:xz_res
            fprintf(1,'%s: Start ix = %d of %d\n',progname,ix,xz_res);
            % Allocate memory to store error from exact_time_domain_solution_refleted_direct_paths.m
            ierr_all=zeros(1,xz_res);
            src_x_i = x(ix);
            parfor iz=1:xz_res
                 %set up source coords and select a g value
                src_z_i = z(iz);
                src_xz_i = [src_x_i src_z_i];
                gi = gf(iz, ix);
                %simulate the signals from source to each receiver
                [h1,ierr_1]=exact_time_domain_solution_reflected_direct_paths(c,src_xz_i,rec_1_xz,tau,omega,gi, ...
                    boundary_type, fign_exact);
                [h2,ierr_2]=exact_time_domain_solution_reflected_direct_paths(c,src_xz_i,rec_2_xz,tau,omega,gi, ...
                    boundary_type, fign_exact);
                                %check for errors
                if ierr_1 || ierr_2
                    ierr_all(iz) = 1;
                    continue
                end %ierr_1 || ierr_2
                %plot if desired
                if(~isempty(fign_exact))
                    fprintf(1,'%s: Pausing. Press ENTER to plot next case.\n',progname);
                    pause
                end

                % calculate tdoa via peak lag
                s1 = h1.s;
                s2 = h2.s;
                fs = gi*omega/(2*pi);
                [t_pk_lag,ierr_3]=plot_ah_ccf_same_samp_freq(s1,s2,fs,fign);
                %check for error
                if ierr_3
                    ierr_all(iz) = 1;
                    continue
                end
                td_i = t_pk_lag;

                % Store tdoa
                if(ierr_all(iz)==0)
                    tdoas(iz,ix)=td_i;
                end


            end % parfor iz=1:n
            if(sum(abs(ierr_all))>0)
                fprintf(1,['%s: At least one error returned from ' ...
                    'exact_time_domain_solution_reflected_direct_paths.m.\n'],...
                    progname);
                fprintf(1,' Pausing so you can fix problem.\n');
                pause
            end
        end %for ix = 1:xz_res
        
        % Make a contour at the inputted distance in difference
        t_level = [td td];
        M = contourc(x, z, tdoas, t_level);
        
        %make sure the isodiachron contours arent empty
        if ~isempty(M)
            % Fix the formatting of the M matrix so that the only points are the points that fall in the contour
            i = 1;
            while i < size(M,2)
                %unpack M's i'th contour
                n_points = M(2,i);
                x_vals = M(1, i+1 : i+n_points);
                z_vals = M(2, i+1 : i+n_points);
                %fill isd_coords
                if isempty(isd_coords{1})
                    isd_coords{1} = [x_vals; z_vals];
                else
                    isd_coords{end+1} = [x_vals; z_vals];
                end
                i = i + n_points + 1;
            end
        else
            %if it is empty, return an error
            fprintf(1,'%s: Isodiachron contains 0 points. Input xz_res value of %d may be too small.\n',progname,xz_res)
            ierr = 1;
            return
        end %if ~isempty(M)    
    otherwise
        fprintf(1,'%s: Software not written for tdoa_type = %d.Pausing...\n',progname,td_type)
        pause
        ierr = 1;

end % switch tdoa_type

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Plot if desired
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
if ~isempty(fign)
    figure;
    hold on;
    grid on;
    axis equal;

    %make a mesh to plot the contour
    [X, Z] = meshgrid(x, z);
    % Plot the isodiachron curve as dashed line
    contour(X, Z, tdoas, t_level, 'k--', 'ShowText', 'off','LineWidth',2)

    % Plot receivers as blue dots
    plot(rec_1_xz(1), rec_1_xz(2), 'bo', 'MarkerSize', 10, 'MarkerFaceColor', 'b');
    plot(rec_2_xz(1), rec_2_xz(2), 'bo', 'MarkerSize', 10, 'MarkerFaceColor', 'b');

    % Plot source as red dot
    plot(src_xz(1), src_xz(2), 'ro', 'MarkerSize', 10, 'MarkerFaceColor', 'r');

    % Set axis limits
    xlim([x_bnds(1), x_bnds(2)]);
    ylim([z_bnds(1), 0]);

    % Add labels and title
    xlabel('x (m)');
    ylabel('z (m)');
    title(['Isodiachron for TDoA = ' num2str(td) 's']);
end %if ~isempty(fign
