% GIVEN
%       1) The xz-coordinates cyllindrical of a source and two receivers
%       2) the tdoa of a signal from the source to the two receivers, dt
%       3) the in-situ speed of sound, c
%       4) the c3d at each of the receivers, c1 and c2
% THIS FUNCTION
%       5) Plots the source location and draws the hyperboloid (locus of points satisfying l2 - l1 = c*dt) and 
%          isodiachrons (loci of points satisfying l2/c2 - l1/c1 = dt), where l2 and l1 are the lengths of a straight 
%          path directly from source to receiver
%
% INPUTS
%
% c               1 x 1.  in-situ speed of sound in water (m/s)
% src_xz          1 x 1.  x = src_xz(1) (m) and z=src_xz(2) (m) are the horizontal and vertical coordinates of a source.
%                         z is 0 at ocean's surface and is positive up. source also located at y=0,  in 3D space.
% rec_1_xz        1 x 2.  The first receiver's horizontal (rec_1_xz(1)) and vertical coordinate (rec_1_xz(2)). Same 
%                         coordinate system as for src_z             
% rec_2_xz        1 x 2.  Same arrangment as rec_1_xz, but for the second receiver
% tau             1 x 1.  emitted pulse is exp(-(t/tau)^2)*cos(omega*t) with tau in seconds and t in seconds
% omega           1 x 1.  See tau above. Units are rad/s
% g_base          1 x 1.  The base g value for each element in the field generated by samp_freq_mult_fied.m, where the
%                         sample frequency of synthsized time series will equal g * omega/(2*pi). g must be >=2.
% g_mult          1 x 1.  The peak multiplier of g to be used near the foci (see samp_freq_mult_field.m). i.e. the 
%                         elements closest to the foci will have a g value of g_base*g_mult
% cheby           1 x 1.  The Chebyshev distance (in units of g field indecies) from the g-field xz index pair nearest  
%                         to the foci which shall be elevated from g_base. I.e. If a focus is nearest to g field's xz 
%                         index pair (2, 2), and cheby = 1, all indecies in the square with opposing corners (1, 1) and 
%                         (3, 3) will be elevated. cheby must be >= 3.
% mult_type       1 x 1.  A numerical identifier to determine how the elevation changes with distance from the xz index
%                         pair nearest to a foci.   0: uniform elevation. each index in range is multiplied by g_mult
%                                                   1: linear. the centermost 3 x 3 index box will be multiplied by
%                                                      g_mult, and each box an additional step outwards will linearly 
%                                                      decrease to g_base
% boundary_type   1 x 1.  1: boundary is like surface of ocean where there are no pressure fluctuations.
%                            There is a direct path and a path reflecting from surface 
%                         2: boundary is hard. Reflected path bounces from hard flat rocks on bottom of ocean.
% x_bnds          1 x 2.  The minimum (x_bnds(1)) and maximum (x_bnds(2)) bounds on the x-coordinate of a region in the
%                         xz-plane for which the source is expected (i.e. the region to be plotted)
% z_bnds          1 x 2.  The minimum (z_bnds(1)) and maximum (z_bnds(2)) bounds on the z-coordinate of a region in the
%                         xz-plane for which the source is expected (i.e. the region to be plotted)
% xz_res          1 x 1   The number of points to divide the x and y bounds into. The higher the number the more points
%                         evaluated at.
% td              1 x 1.  The time difference of arrival of a signal between 2 receivers
% td_type         1 x 1.  Parameter to identify how the tdoa was determined.
%                           0: difference in arrival times of peaks of incoming energy received by each receiver
%                           1: peak lag given by cross correlation of the signal received by the receivers
% fign            1 x 1.  Figure number for plot. If empty, no plots shown.
%
% OUTPUTS
%
% ierr            0: No error detected. 1: otherwise
%
function [min_hyp_dist, ierr]=plot_loci_rec_pair_cst_c(c,src_xz,rec_1_xz, rec_2_xz, tau, omega, g_base, ...
    g_mult, cheby, mult_type, boundary_type, x_bnds, z_bnds, xz_res, td, td_type, fign)

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Preliminary Steps
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
progname='plot_loci_rec_pair_cst_c.m';
%fprintf(1,'%s: See cags6121.mat to  debug. Pausing\n',progname);save  cags6121;pause

dotest=0;
if(dotest==1)
    fprintf(1,'%s: Test case. Press Enter to continue\n',progname);pause
    c=1500;
    
    scenario=9;
    switch scenario

        case 1 %no hyperbola
            src_xz=[0 -20];
            rec_1_xz=[8 -8];
            rec_2_xz=[38 -8];
            tau=0.025;
            omega=93*2*pi;
            g_base=10000;
            g_mult = 1;
            boundary_type=1;
            x_bnds = [-4 20];
            z_bnds = [-24 0];
            xz_res = 25;
        
        case 2 % hyperbola present, smooth isd, min_dist = 1.5486
            src_xz=[0 -20];
            rec_1_xz=[35 -8];
            rec_2_xz=[35 -13];
            tau=0.025;
            omega=93*2*pi;
            g_base=10000;
            g_mult = 1;
            boundary_type=1;
            x_bnds = [-4 40];
            z_bnds = [-24 0];
            xz_res = 30;

        case 3 % hyperbola present, funky isd, min_dist = 14.6373
            src_xz=[0 -20];
            rec_1_xz=[42 -18];
            rec_2_xz=[11 -18];
            tau=0.025;
            omega=100*2*pi;
            g_base=10000;
            g_mult = 1;
            boundary_type=1;
            x_bnds = [-4 60];
            z_bnds = [-30 0];
            xz_res = 60;
        case 4 % hyperbola present, funky isd, min_dist = 24.0913
            src_xz=[0 -50];
            rec_1_xz=[12 -19];
            rec_2_xz=[41 -19];
            tau=0.025;
            omega=100*2*pi;
            g_base=5000;
            g_mult = 1;
            boundary_type=1;
            x_bnds = [-4 60];
            z_bnds = [-60 0];
            xz_res = 50;

        case 5 %no hyperbola, vlow vlow
            src_xz=[5 -50];
            rec_1_xz=[110 -45];
            rec_2_xz=[215 -45];
            tau=0.025;
            omega=93*2*pi;
            g_base=2000;
            g_mult = 1;
            boundary_type=1;
            x_bnds = [-4 350];
            z_bnds = [-80 0];
            xz_res = 50;            

         case 6 %hyp
            src_xz=[5 -50];
            rec_1_xz=[110 -45];
            rec_2_xz=[290 -45];
            tau=0.025;
            omega=93*2*pi;
            g_base=10000;
            g_mult = 1;
            boundary_type=1;
            x_bnds = [-4 350];
            z_bnds = [-80 0];
            xz_res = 50;  
        case 7 %no hyperbola, not too bad  isds
            src_xz=[5 -50];
            rec_1_xz=[105 -40];
            rec_2_xz=[215 -40];
            tau=0.025;
            omega=93*2*pi;
            g_base=2000;
            g_mult = 1;
            boundary_type=1;
            x_bnds = [-4 350];
            z_bnds = [-80 0];
            xz_res = 50;  
        case 8 %no hyperbola USE THIS
            src_xz=[5 -50];
            rec_1_xz=[80 -70];
            rec_2_xz=[250 -70];
            tau=0.025;
            omega=93*2*pi;
            g_base=10000;
            g_mult = 1;
            boundary_type=1;
            x_bnds = [-50 350];
            z_bnds = [-120 0];
            xz_res = 45;
        case 9 % hyp and isd, USE THIS
            src_xz=[5 -50];
            rec_1_xz=[72 -34];
            rec_2_xz=[130 -34];
            tau=0.025;
            omega=93*2*pi;
            g_base=5000;
            g_mult = 1;
            boundary_type=1;
            x_bnds = [-50 350];
            z_bnds = [-120 0];
            xz_res = 25;


        otherwise
        fprintf(1,'%s: software not written for scenario=%d\n',progname,scenario);
        pause
    end % switch scenario
    %calculate td
    g = g_base * g_mult;
    fign_empty = [];
    [h1,~]=exact_time_domain_solution_reflected_direct_paths(c,src_xz,rec_1_xz,tau,omega,g,boundary_type, ...
        fign_empty);
    [h2,~]=exact_time_domain_solution_reflected_direct_paths(c,src_xz,rec_2_xz,tau,omega,g,boundary_type, ...
        fign_empty);
    td_type = 0;
    if td_type == 0
        td = h2.t_r - h1.t_r;
    elseif td_type == 1
        s1 = h1.s;
        s2 = h2.s;
        fs = g*omega/(2*pi);
        [td,ierr]=plot_ah_ccf_same_samp_freq(s1,s2,fs,fign_empty);
        if ierr == 1
            fprintf(1,'%s: ierr = 1 for plot_ah_ccf_same_samp_freq.m in preliminary calculation of TDoA.\n', ...
                progname)
            return
        end
    end
    
    
    fign=4;
else
    fign_empty =[];
end

% Initialize outputs
ierr=0;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% create the loci
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%get the hyperbola loci
dist_diff = c*td;
dist_btw_recs = norm(rec_1_xz - rec_2_xz);
%check if hyperbola can't exist
[hyp_x_coords,hyp_z_coords] = hyperbola_2d_xz(rec_1_xz, rec_2_xz, dist_diff, x_bnds, z_bnds, xz_res, fign_empty);
%check if no hyperbola found
if isempty(hyp_x_coords)
    fprintf(1, ['%s: No hyperbola detected. dist_diff = %f exceeds limit for receivers seperated by %f (m),\n ' ...
        'subject to the following parameters:\n' ...
        '    td = %s (s),    rec_1_xz = [%f %f] (m),    rec_2_xz = [%f %f] (m)\n'],progname,dist_diff,  ...
        dist_btw_recs,td,rec_1_xz(1), rec_1_xz(2), rec_2_xz(1),rec_2_xz(2))
    min_hyp_dist = nan;
else % if there is a hyperbola, find the closest distance from the source to i  
    % Assume src_xz = [x_src, z_src]
    x_src = src_xz(1);
    z_src = src_xz(2);
    % Compute distance from source to each hyperbola point
    distances = sqrt((hyp_x_coords - x_src).^2 + (hyp_z_coords - z_src).^2);
    % Find the minimum distance
    min_hyp_dist = min(distances);
end %isempty(hyp_x_coords)
%get the isodiachron loci
[isd_coords, ierr] = isodiachron_xz_from_tdoa_cst_c(c,src_xz,rec_1_xz, rec_2_xz, tau, omega, g_base, g_mult, ...
    cheby, mult_type, boundary_type, x_bnds, z_bnds, xz_res, td, td_type, fign_empty);
if ierr
    fprintf(1,'%s: Error detected in isodiachron_xz_from_tdoa.m',progname)
    return
end
%create a parameter for minimum distance between source and isodiachron
min_isd_dist = inf;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% plot
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
if ~isempty(fign)
    figure(fign); clf(fign);
    hold on;
    grid on;
    axis equal;

    % Plot hyperbola (solid black line)
    h_hyp = plot(hyp_x_coords, hyp_z_coords, 'k--', 'LineWidth', 2);

    % Plot isodiachrons (dashed black lines)
    h_isod = [];  % handle for legend
    for i = 1:length(isd_coords)  % skip isd_coords{1} if empty
        x_vals = isd_coords{i}(1, :);
        z_vals = isd_coords{i}(2, :);
        h = plot(x_vals, z_vals, 'k-', 'LineWidth', 1.5);
        if isempty(h_isod)
            h_isod = h;  % only store the first for legend
        end
        %find the minimum distance between source and an isodiachron
        x_src = src_xz(1);
        z_src = src_xz(2);
        distances = sqrt((x_vals - x_src).^2 + (z_vals - z_src).^2);
        % Find the minimum distance
        min_dist = min(distances);
        if min_dist < min_isd_dist
            min_isd_dist = min_dist;
        end
    end %i = 1:length(isd_coords)
    %print the min distance to isodiachron if fign isnt empty
    % Plot receivers (red dots)
    h_rec1 = plot(rec_1_xz(1), rec_1_xz(2), 'ro', 'MarkerSize', 10, 'MarkerFaceColor', 'r');
    h_rec2 = plot(rec_2_xz(1), rec_2_xz(2), 'ro', 'MarkerSize', 10, 'MarkerFaceColor', 'r');

    % Plot source (blue dot)
    h_src = plot(src_xz(1), src_xz(2), 'bo', 'MarkerSize', 10, 'MarkerFaceColor', 'b');

    % Set axis bounds
    xlim([x_bnds(1), x_bnds(2)]);
    ylim([z_bnds(1), 0]);

    % Add labels and title
    xlabel('x (m)');
    ylabel('z (m)');
    title(['Hyperbola and Isodiachrons for TDoA = ' num2str(td, '%.5f') ' s']);

    % Add legend
    if ~isempty(hyp_x_coords) %only inlcude hyperbola in legend if included in plot
        legend([h_src, h_rec1, h_hyp, h_isod], ...
            {'Source', 'Receivers', 'Hyperbola', 'Isodiachrons'}, ...
            'Location', 'best');
    else
        legend([h_src, h_rec1, h_isod], ...
            {'Source', 'Receivers', 'Isodiachrons'}, ...
            'Location', 'best');
    end
    hold off
end

