% Creates a field of values for the sample frequency multiplier g, with elevated values near specified points of
% interest. As in exact_time_domain_solution_reflected_direct_paths.m, the sample frequency of a signal's time series,
% fs, is fs = g*omega/(2*pi). g >=2.
%
% INPUTS
%
% foci_xz     n x 2.      foci_xz(i,1) and foci_xz(i,2) are the x (m) and z (m) Cartesian coordinates of the i'th focus
%                         for an elevated area of the g field.
% x_bnds      1 x 2.      The minimum (x_bnds(1)) and maximum (x_bnds(2)) bounds on the x-coordinate of a region in the
%                         xz-plane for which the g field is to be generated
% z_bnds      1 x 2.      The minimum (z_bnds(1)) and maximum (z_bnds(2)) bounds on the z-coordinate of a region in the
%                         xz-plane for which the g field is to begenerated
% nx          1 x 1.      The number of x indecies to be used in the field
% nz          1 x 1.          "       " z     "       "       "       "
% g_base      1 x 1.      The base g value for each element in the field generated by samp_freq_mult_fied.m, where the
%                         sample frequency of synthsized time series will equal g * omega/(2*pi). g must be >=2.
% g_mult      1 x 1.      The peak multiplier of g to be used near the foci (see samp_freq_mult_field.m). i.e. the 
%                         elements closest to the foci will have a g value of g_base*g_mult
% cheby       1 x 1.      The Chebyshev distance (in units of g field indecies) from the g-field xz index pair nearest  
%                         to the foci which shall be elevated from g_base. I.e. If a focus is nearest to g field's xz 
%                         index pair (2, 2), and cheby = 1, all indecies in the square with opposing corners (1, 1) and 
%                         (3, 3) will be elevated. cheby must be >= 3.
% mult_type   1 x 1.      A numerical identifier to determine how the elevation changes with distance from the xz index
%                         pair nearest to a foci.   0: uniform elevation. each index in range is multiplied by g_mult
%                                                   1: linear. the centermost 3 x 3 index box will be multiplied by
%                                                      g_mult, and each box an additional step outwards will linearly 
%                                                      decrease to g_base
%
% OUTPUTS
%
% gf          nz x nx.      the field of g-values (see g_base above)
% ierr        0: No error detected. 1: otherwise
%
function [gf,ierr]=samp_freq_mult_field(foci_xz,x_bnds,z_bnds,nx,nz,g_base, g_mult, cheby, mult_type)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Preliminary Steps
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
progname='samp_freq_mult_field.m';
% fprintf(1,'%s: See cags7141.mat to  debug. Pausing\n',progname);save  cags7141;pause

dotest=0;
if(dotest==1)
    fprintf(1,'%s: Test case. Press Enter to continue\n',progname);pause
    
    scenario=1;
    switch scenario
             
        otherwise
            fprintf(1,'%s: software not written for scenario=%d\n',progname,scenario);
            pause
    end % switch scenario
    
    fign=1;
end

% Initialize outputs
gf = NaN(nz, nx);
ierr=0;

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% generate the g field
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Create a grid to set g at each point on grid
x = linspace(x_bnds(1), x_bnds(2), nx);
z = linspace(z_bnds(1), z_bnds(2), nz);

% Initialize gf with base value
gf = g_base * ones(nz, nx);

% Loop through each focus
for r = 1:size(foci_xz,1)
    rx = foci_xz(r,1);
    rz = foci_xz(r,2);

    % Find nearest grid index in x and z
    [~, ix] = min(abs(x - rx));
    [~, iz] = min(abs(z - rz));

    %elevation process depends on mult type
    switch mult_type

        %uniform
        case 0
            for dx = -cheby:cheby
                for dz = -cheby:cheby
                    ix_new = ix + dx;
                    iz_new = iz + dz;
                    %ensure the new index pair isnt out of bounds
                    if ix_new >= 1 && ix_new <= nx && iz_new >= 1 && iz_new <= nz
                        %elevate the box to the max
                        gf(iz_new, ix_new) = g_mult*g_base;

                       
                    end
                end % for dz = -cheby:cheby
            end % for dx = -cheby:cheby

        %linear
        case 1
            % Boost at (ix, iz) and its four surrounding cells (if within bounds)
            for dx = -cheby:cheby
                for dz = -cheby:cheby
                    ix_new = ix + dx;
                    iz_new = iz + dz;
                    %ensure the new index pair isnt out of bounds
                    if ix_new >= 1 && ix_new <= nx && iz_new >= 1 && iz_new <= nz
                        % find the Chebyshev index distance of the new index pair
                        cdist = max(abs(dx), abs(dz));
                        %elevate the 3 x 3 box to the max
                        if cdist == 0
                            gf(iz_new, ix_new) = g_mult * g_base;
                        %linearly decrease the max elevation
                        elseif (1 <= cdist) && (cdist<= cheby)
                            mult = g_mult*(cheby-cdist+1)/(cheby);
                            %only change the g value if  it is higher than before
                            g = mult*g_base;
                            if ceil(g) > gf(iz_new, ix_new)
                                gf(iz_new, ix_new) = ceil(g);
                            end
                        else
                            fprintf(1,['%s: Error, index pair (iz, ix) = (%d, %d) is greater then Chebyshev %d ' ...
                                'from foci index pair (iz, ix) = (%d, %d)\n'],progname,iz_new,ix_new,cheby,iz,ix)
                            ierr = 1;
                            return
                        end
                    end
                end % for dz = -cheby:cheby
            end % for dx = -cheby:cheby

        otherwise
            fprintf(1,'%s: software not written for scenario=%d\n',progname,scenario);
    end % switch mult_type
end % for r = 1:size(foci_xz,1)