% Calculates the differene between the tdoa calculated via cross-correlation and the tdoa via the peak-to-peak method,
% returning a field of these differences at each point in a grid.
%
% INPUTS
%
% c               1 x 1.            in-situ speed of sound in water (m/s)
% rec_1_xz        1 x 2.            The first receiver's (x (m), z (m)) coordinates. x is the horizontal coordinate, and 
%                                   z is the vertical coordinate defined positive up with z =  0 at the ocean's surface          
% rec_2_xz        1 x 2.            Same as rec_1_xz, but for the second receiver
% tau             1 x 1.            emitted pulse is exp(-(t/tau)^2)*cos(omega*t) with tau in seconds and t in seconds
% omega           1 x 1.            See tau above. Units are rad/s
% g_base          1 x 1.            The base g value for each element in the field generated by samp_freq_mult_fied.m, 
%                                   where the sample frequency of synthsized time series will equal g * omega/(2*pi). 
%                                   g must be >=2.
% g_mult          1 x 1.            The peak multiplier of g to be used near the foci (see samp_freq_mult_field.m). 
%                                   i.e. the elements closest to the foci will have a g value of g_base*g_mult
% cheby           1 x 1.            The Chebyshev distance (in units of g field indecies) from the g-field xz index pair
%                                   nearest to the foci which shall be elevated from g_base. I.e. If a focus is nearest 
%                                   to g field's xz index pair (2, 2), and cheby = 1, all indecies in the square with 
%                                   opposing corners (1, 1) and (3, 3) will be elevated. cheby must be >= 3.
% mult_type       1 x 1.            A numerical identifier to determine how the elevation changes with distance from the 
%                                   xz index pair nearest to a foci.   
%                                       0: uniform elevation. each index in range is multiplied by g_mult
%                                       1: linear. the centermost 3 x 3 index box will be multiplied by
%                                          g_mult, and each box an additional step outwards will linearly 
%                                          decrease to g_base
% boundary_type   1 x 1.            1: boundary is like surface of ocean where there are no pressure fluctuations.
%                                      There is a direct path and a path reflecting from surface 
%                                   2: boundary is hard. Reflected path bounces from hard flat rocks on bottom of ocean.
% x_bnds          1 x 2.            The minimum (x_bnds(1)) and maximum (x_bnds(2)) bounds on the x-coordinate of a 
%                                   region in the xz-plane for which the source is expected (i.e. the region to be 
%                                   plotted)
% z_bnds          1 x 2.            The minimum (z_bnds(1)) and maximum (z_bnds(2)) bounds on the z-coordinate of a 
%                                   region in the xz-plane for which the source is expected (i.e. the region to be 
%                                   plotted)
% xz_res          1 x 1.            The number of points to divide the x and z bounds into. The higher the number, the 
%                                   more points evaluated at.
% fnam_out        1 x 1.            String filename (sans extension) for the output figure's .fig and .jpeg files
% fign            1 x 1.            Figure number for plot. If empty, no plots shown.
%
% OUTPUTS
%
% tdoa_diff       xz_res x xz_res.  each tdoa_diff(i,j) = (tdoa calculated via ccf) - (tdoa calculated via peak to peak)
%                                   at the i'th increment of x and the j'th increment of z (increments determined by 
%                                   x_bnds,  z_bnds, and xz_res).
%
% ierr                              0: No error detected. 1: otherwise

function [tdoa_diffs, ierr] = tdoa_diffs_cst_c(c,rec_1_xz, rec_2_xz, tau, omega, g_base, g_mult, cheby, mult_type, ...
    boundary_type, x_bnds, z_bnds, xz_res,fnam_out,fign)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% PRELIMINARY STEPS
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
progname='tdoa_diffs_cst_c.m';
%fprintf (1, '%s: See cags7021.mat to debug.  Pausing\n', progname);save cags7021; pause

dotest=0;
if(dotest==1)
    fprintf(1,'%s: Test case. Press Enter to continue\n',progname);pause
    c=1500;
    
    scenario=2;
    switch scenario

        case 1 %no hyperbola USE THIS
            rec_1_xz=[80 -70];
            rec_2_xz=[250 -70];
            tau=0.025;
            omega=93*2*pi;
            g_base=2000;
            g_mult = 30;
            cheby = 5;
            mult_type = 0;
            boundary_type=1;
            x_bnds = [-500 500];
            z_bnds = [-120 -1];
            xz_res = 150; 

        case 2
            rec_1_xz=[80 -70];
            rec_2_xz=[250 -70];
            tau=0.025;
            omega=93*2*pi;
            g_base=2000;
            g_mult = 30;
            cheby = 5;
            mult_type = 0;
            boundary_type=1;
            x_bnds = [-50 380];
            z_bnds = [-120 -1];
            xz_res = 150;

        otherwise
        fprintf(1,'%s: software not written for scenario=%d\n',progname,scenario);
        pause
    end % switch scenario
    fign=11;
    tt = '';
    fnam_out = ['dotest_' tt num2str(fign)];
end

% Initialize outputs
tdoa_diffs = nan(xz_res,xz_res);
ierr = 0;


%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Do work
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Create a grid to set g at each point on grid
x = linspace(x_bnds(1), x_bnds(2), xz_res);
z = linspace(z_bnds(1), z_bnds(2), xz_res);
% make a field of 'g' values at each grdipoint to optimize time
foci_xz = [rec_1_xz; rec_2_xz];
[gf,ierr]=samp_freq_mult_field(foci_xz,x_bnds,z_bnds,xz_res,xz_res,g_base, g_mult, cheby, mult_type);
if ierr ==1
    fprintf(1,'%s: Error detected in samp_freq_mult_field.m\m',progname)
    return
end
%iterate through the gridpoints, storing the result in tdoa_diffs
for ix = 1:xz_res
    fprintf(1,'%s: Start ix = %d of %d\n',progname,ix,xz_res);
    % Allocate memory to store error from exact_time_domain_solution_refleted_direct_paths.m
    ierr_all=zeros(1,xz_res);
    src_x_i = x(ix);
    parfor iz=1:xz_res
        %set up source coords and select a g value
        src_z_i = z(iz);
        src_xz_i = [src_x_i src_z_i];
        gi = gf(iz, ix);
        %simulate the signals from source to each receiver
        fign_empty = [];
        [h1,ierr_1]=exact_time_domain_solution_reflected_direct_paths(c,src_xz_i,rec_1_xz,tau,omega,gi, ...
            boundary_type, fign_empty);
        [h2,ierr_2]=exact_time_domain_solution_reflected_direct_paths(c,src_xz_i,rec_2_xz,tau,omega,gi, ...
            boundary_type, fign_empty);
        %check for errors
        if ierr_1 || ierr_2
            ierr_all(iz) = 1;
            continue
        end %ierr_1 || ierr_2

        %calculate tdoa via peak to peak
        td_p2p = h2.t_r - h1.t_r;

        % calculate tdoa via ccf
        s1 = h1.s;
        s2 = h2.s;
        fs = gi*omega/(2*pi);
        [t_pk_lag,ierr_3]=plot_ah_ccf_same_samp_freq(s1,s2,fs,fign);
        %check for error
        if ierr_3
            ierr_all(iz) = 1;
            continue
        end
        td_ccf = t_pk_lag;
        

        % Store difference
        if(ierr_all(iz)==0)
            tdoa_diffs(ix,iz) = td_ccf - td_p2p;
        end
 

    end % parfor iz=1:n
    if(sum(abs(ierr_all))>0)
        fprintf(1,['%s: At least one error returned from ' ...
            'exact_time_domain_solution_reflected_direct_paths.m.\n'],...
            progname);
        fprintf(1,' Pausing so you can fix problem.\n');
        pause
    end
end %for ix = 1:xz_res

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Plot (if desired)
%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
if ~isempty(fign)
    figure(fign);
    clf(fign);
    %make the tdoa_diffs surface
    surf(x,z,tdoa_diffs','facealpha',0.5,'EdgeColor','none');
    title(tt)
    xlabel('x (m)');
    ylabel('z (m)');
    hold on;
    % find the max time difference and plot the sources and receivers at a t value above it
    t_max = max(tdoa_diffs(:));
    t_min = min(tdoa_diffs(:));
    t_val = t_max + 0.01*(t_max - t_min);
    %plot3(src_xz(1),src_xz(2),t_val,'k.','MarkerSize',27)
    plot3(rec_1_xz(1),rec_1_xz(2),t_val,'ko','MarkerSize',10,'LineWidth',1)
    plot3(rec_2_xz(1),rec_2_xz(2),t_val,'ko','MarkerSize',10,'LineWidth',1)

    %format the figure
    %view(gca, 2);
    grid on
    colormap('gray');
    cb = colorbar(gca);
    ylabel(cb, '{\Delta}t');
end %if ~isempty(fign)

%save the output figure
saveas(figure(fign), fnam_out,'fig')
exportgraphics(figure(fign),[fnam_out '.jpeg'], 'Resolution', 600);
